export const currentIPOs: any[] = [
  {
    name: "Bharat Coking Coal",
    boardType: "Mainboard",
    isLive: false,
    allotmentAwaited: true,
    offerDate: "Jan 9, 2026 - Jan 13, 2026",
    offerPrice: "21-23",
    lotSize: "600",
    subscription: "8.14 times",
    expPremium: "10-10.1 (43.48%)",
  },
  {
    name: "Amagi Media Labs",
    boardType: "Mainboard",
    isLive: true,
    allotmentAwaited: false,
    offerDate: "Jan 20, 2026 - Jan 24, 2026",
    offerPrice: "200-210",
    lotSize: "50",
    subscription: "5.2 times",
    expPremium: "15-16 (35.5%)",
  },
  {
    name: "Pranav Constructions",
    boardType: "Mainboard",
    isLive: false,
    allotmentAwaited: false,
    offerDate: "Jan 25, 2026 - Jan 29, 2026",
    offerPrice: "100-105",
    lotSize: "150",
    subscription: "0 times",
    expPremium: "8-9 (20%)",
  },
  {
    name: "Cordeila Cruises (Waterways Leisure Tourism)",
    boardType: "Mainboard",
    isLive: false,
    allotmentAwaited: false,
    offerDate: "Jan 30, 2026 - Feb 3, 2026",
    offerPrice: "175-180",
    lotSize: "80",
    subscription: "0 times",
    expPremium: "12-13 (28%)",
  },
  {
    name: "Clean Max Enviro Energy Solutions",
    boardType: "Mainboard",
    isLive: false,
    allotmentAwaited: false,
    offerDate: "Feb 5, 2026 - Feb 9, 2026",
    offerPrice: "125-130",
    lotSize: "120",
    subscription: "0 times",
    expPremium: "10-11 (25%)",
  },
  {
    name: "Fractal Analytics",
    boardType: "Mainboard",
    isLive: false,
    allotmentAwaited: false,
    offerDate: "Feb 10, 2026 - Feb 14, 2026",
    offerPrice: "300-310",
    lotSize: "40",
    subscription: "18-20 (40%)",
    expPremium: "18-20 (40%)",
  },
];
